### ISSUE TITLE
server 下 run start 报错

### ISSUE THREAD

**Issue by emila-github** [tencentyun/wafer2-quickstart-nodejs#11]
报错信息如下：

15:41:07 0|session  | F:\xxx\xxx\xxx\server\middlewares\response.js:6
15:41:07 0|session  | module.exports = async function (ctx, next) {
15:41:07 0|session  |                        ^^^^^^^^
15:41:07 0|session  | SyntaxError: Unexpected token function
15:41:07 0|session  |     at Object.exports.runInThisContext (vm.js:76:16)
15:41:07 0|session  |     at Module._compile (module.js:542:28)
15:41:07 0|session  |     at Object.Module._extensions..js (module.js:579:10)
15:41:07 0|session  |     at Module.load (module.js:487:32)
15:41:07 0|session  |     at tryModuleLoad (module.js:446:12)
15:41:07 0|session  |     at Function.Module._load (module.js:438:3)
15:41:07 0|session  |     at Module.require (module.js:497:17)
15:41:07 0|session  |     at require (internal/module.js:20:19)
15:41:07 0|session  |     at Object.<anonymous> (F:\xxx\xxx\xxx\server\app.js:4:18)
15:41:07 0|session  |     at Module._compile (module.js:570:32)
[2018-06-14 15:41:07] PM2 log: App [session] with id [0] and pid [14512], exited with code [1] via signal [SIGINT]
15:41:07 PM2        | App [session] with id [0] and pid [14512], exited with code [1] via signal [SIGINT]
[2018-06-14 15:41:07] PM2 log: Starting execution sequence in -fork mode- for app name:session id:0
15:41:07 PM2        | Starting execution sequence in -fork mode- for app name:session id:0
[2018-06-14 15:41:07] PM2 log: App name:session id:0 online
15:41:07 PM2        | App name:session id:0 online

注：
node: v6.9.2

**Comment by jas0ncn** [comment]
Node版本请升级到8以上

**Comment by emila-github** [comment]
node  v8.11.2
npm  5.6.0
