### ISSUE TITLE
本地server下运行npm start报错

### ISSUE THREAD

**Issue by emila-github** [tencentyun/wafer2-quickstart-nodejs#12]
18:34:10 0|session  | Error: ERR_INIT_SDK_LOST_CONFIG
18:34:10 0|session  |     at init (f:\xxx\xxx\server\node_modules\wafer-node-sdk\index.js:48:190)
18:34:10 0|session  |     at Object.<anonymous> (f:\xxx\xxx\server\qcloud.js:36:18)
18:34:10 0|session  |     at Module._compile (module.js:652:30)
18:34:10 0|session  |     at Object.Module._extensions..js (module.js:663:10)
18:34:10 0|session  |     at Module.load (module.js:565:32)
18:34:10 0|session  |     at tryModuleLoad (module.js:505:12)
18:34:10 0|session  |     at Function.Module._load (module.js:497:3)
18:34:10 0|session  |     at Module.require (module.js:596:17)
18:34:10 0|session  |     at require (internal/module.js:11:18)
18:34:10 0|session  |     at Object.<anonymous> (f:\xxx\xxx\server\controllers\message.js:1:103)
[2018-06-15 18:34:10] PM2 log: App [session] with id [0] and pid [18896], exited with code [1] via signal [SIGINT]
[2018-06-15 18:34:10] PM2 log: Starting execution sequence in -fork mode- for app name:session id:0

**Comment by emila-github** [comment]
node v8.11.2
npm 5.6.0

**Comment by jas0ncn** [comment]
参考文档补充一下配置：https://cloud.tencent.com/document/product/619/11445
