### ISSUE TITLE
登录出现问题

### ISSUE THREAD

**Issue by fathernima** [tencentyun/wafer2-quickstart-nodejs#15]
### 微信安卓端和模拟器以及远程调试的登录结果三者都不一样

- **微信安卓端：**

type:"ERR_LOGIN_FAILED",message:" 登录失败，可能是网络错误或者服务器发生异常"

- **模拟器：**

清除所有缓存后，首次点击登录会出错：type: "ERR_WX_GET_USER_INFO", message: "获取微信用 
 户信息失败，请检查网络状态"
首次点击登录出错后，再点击登录即可登录成功

- **远程调试：**

可以顺利登录

（不是体验版小程序，有appid和secret；IOS端未测试）

**Comment by jas0ncn** [comment]
检查一下是否将 URL 地址加进微信安全地址了。。。

**Comment by fathernima** [comment]
没太听明白 = =

URL是指这些吧：

        // 登录地址，用于建立会话
        loginUrl: `${host}/weapp/login`,

        // 测试的请求地址，用于测试会话
        requestUrl: `${host}/weapp/user`,

        // 测试的信道服务地址
        tunnelUrl: `${host}/weapp/tunnel`,

        // 上传图片接口
        uploadUrl: `${host}/weapp/upload``

**微信安全地址是指什么？**

**Comment by fathernima** [comment]
哦我明白了，在Wiki里面看到解释了
不好意思是我疏忽了😁
谢谢
