### ISSUE TITLE
手机端登录出现ERR_LOGIN_FAILED

### ISSUE THREAD

**Issue by night1008** [tencentyun/wafer2-quickstart-nodejs#2]
为什么在开发者工具上可以正常登录，在手机上打开小程序测试登录就出现ERR_LOGIN_FAILED了呢

**Comment by jas0ncn** [comment]
https://github.com/tencentyun/wafer2-startup/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E7%9C%9F%E6%9C%BA%E9%A2%84%E8%A7%88%E7%9A%84%E6%97%B6%E5%80%99%E6%8F%90%E7%A4%BA%E7%BD%91%E7%BB%9C%E5%87%BA%E9%94%99

**Comment by night1008** [comment]
@jas0ncn 多谢 😅
