### ISSUE TITLE
开通环境失败

### ISSUE THREAD

**Issue by chenchongji** [tencentyun/wafer2-quickstart-nodejs#3]
找不到"建立腾讯云Node.js启动模板"，只有"建立普通快速启动模板"

<img width="404" alt="2018-01-10 3 50 54" src="https://user-images.githubusercontent.com/13236841/34761317-36ab6fd8-f61e-11e7-9cc4-6bbf3e77e4d0.png">

**Comment by iMuFeng** [comment]
同这个问题

**Comment by jas0ncn** [comment]
需要先绑定腾讯云账号和微信小程序账号才会有这个选项。
