### ISSUE TITLE
session获取的问题

### ISSUE THREAD

**Issue by ganshenml** [tencentyun/wafer2-quickstart-nodejs#4]
https://github.com/tencentyun/wafer2-quickstart-nodejs/blob/master/client/vendor/wafer2-client-sdk/lib/login.js
文档中的session获取是一个key为 'weapp_session_' + constants.WX_SESSION_MAGIC_ID 的值，而在代码中却写下了这样的回调处理：
```
  wx.checkSession({
            success: function () {
                options.success(session.userInfo);
            }
```
很明显，此时的session.userInfo是undefined的，为啥会这样回调处理呢？

**Comment by jas0ncn** [comment]
感谢提醒，已经修正！
