### ISSUE TITLE
说说我遇到的问题

### ISSUE THREAD

**Issue by prettydt** [tencentyun/wafer2-quickstart-nodejs#7]
1 小程序套餐没有开远程连接，腾讯的工程师还各种连接，开都没开，怎么连接？

2 KOA部分的代码没法测试，还加入了个恶心的用户信息，保存session，然后返回，我不知道这个逻辑是什么，客户端已经login了，远程还有login?

3 域名没有备案根本就不能用于生产，那他妈当时我买的时候为什么不跟我说，买完之后发现根本不能用，备案要一个月
垃圾的小程序套餐，要不你当时就让我买云主机，买了个小程序套餐各种不能用，垃圾！！

**Comment by jas0ncn** [comment]
1. 我们特意没提供的远程连接功能哈。和普通的云主机不同，可能是你提交错了工单的团队。
2. 后端代码是可以测试的，只是 Tunnel 不行，另外部署到开发环境也可以通过远程调试去调试的。
3. 备案不能用于正式访问这个是国家的规定，也是微信的限制，我们的提示不够清晰，这个我们最近加一下，感谢提醒！

**Comment by prettydt** [comment]
您好，谢谢您的回复

其实我的需求是这么回事：

我把数据存在mysql里面，数据是从python来的，我每天导入，然后用小程序访问这个mysql,从里面读数，做汇总，提供给客户服务，类似于云函数这种东西，我又不会nodejs,php,没有别的业务逻辑，我就想让你们推荐一下，我这种需求应该买哪种腾讯云的服务，回复为盼.

**Comment by jas0ncn** [comment]
你可以购买腾讯云的云数据库，你本机和小程序后端都使用云数据库的外网地址访问。
