### ISSUE TITLE
开发过程中的问题

### ISSUE THREAD

**Issue by perseveringman** [tencentyun/wafer2-quickstart-nodejs#9]
1.数据库经常会“假性重置”，现象是变为初始化时啥也没有的数据库，过一段时间又会恢复回来。前两次遇到的时候给我吓坏了，后面已经习以为常。。。
2.接口经常502，需要频繁的重新上传server代码

**Comment by jas0ncn** [comment]
开发环境7天没有上传会自动回收，重新上传会恢复。生产环境才是用来部署业务的。开发环境是用来开发临时使用的。
